import { ErrorSeverity, SystemErrorRecord, SystemErrorSource } from './ErrorSeverity';
import { AppError } from './AppError';
import { logger } from '../utils/logger';
import { systemErrorRepository } from '../repositories/SystemErrorRepository';

export interface RecordErrorInput {
  severity: ErrorSeverity;
  source: SystemErrorSource;
  service: string;
  operation: string;
  message: string;
  details?: Record<string, unknown>;
  incidentId?: string;
  ambulanceId?: string;
  hospitalId?: string;
}

export class SystemErrorRegistry {
  private static instance: SystemErrorRegistry;
  private errorRecords: SystemErrorRecord[] = [];
  private idCounter = 1;

  private constructor() {}

  public static getInstance(): SystemErrorRegistry {
    if (!SystemErrorRegistry.instance) {
      SystemErrorRegistry.instance = new SystemErrorRegistry();
    }
    return SystemErrorRegistry.instance;
  }

  /**
   * Records a REAL system error event generated by backend operations into persistent storage.
   */
  public recordError(input: RecordErrorInput): SystemErrorRecord {
    const record: SystemErrorRecord = {
      id: `ERR-${Date.now()}-${this.idCounter++}`,
      timestamp: new Date().toISOString(),
      severity: input.severity,
      source: input.source,
      service: input.service,
      operation: input.operation,
      message: input.message,
      details: input.details,
      incidentId: input.incidentId,
      ambulanceId: input.ambulanceId,
      hospitalId: input.hospitalId,
      resolved: false,
    };

    this.errorRecords.push(record);

    logger.error(`[SYSTEM_ERROR_LOGGED] [${record.severity}] [${record.source}] ${record.message}`, {
      errorId: record.id,
      service: record.service,
      operation: record.operation,
    });

    // Broadcast live error event to Admin Command Center via WebSockets
    try {
      const { webSocketManager } = require('../server/websocket');
      webSocketManager.broadcastSystemError(record);
    } catch {
      // ignore
    }

    // Asynchronously persist to PostgreSQL DB
    systemErrorRepository.recordError(record).catch(() => {});

    return record;
  }

  /**
   * Records a thrown AppError.
   */
  public recordAppError(error: AppError): SystemErrorRecord {
    return this.recordError({
      severity: error.severity,
      source: error.source,
      service: error.service,
      operation: error.operation,
      message: error.message,
      details: error.details,
      incidentId: error.incidentId,
      ambulanceId: error.ambulanceId,
      hospitalId: error.hospitalId,
    });
  }

  /**
   * Retrieve genuine logged system error records for Admin Command Center.
   */
  public async getRecordedErrors(filter?: {
    severity?: ErrorSeverity;
    source?: SystemErrorSource;
    resolved?: boolean;
  }): Promise<SystemErrorRecord[]> {
    const dbErrors = await systemErrorRepository.getRecordedErrors(filter);
    const dbIds = new Set((dbErrors || []).map((e) => e.id));
    let memoryErrors = [...this.errorRecords].filter((e) => !dbIds.has(e.id));
    if (filter) {
      if (filter.severity) {
        memoryErrors = memoryErrors.filter((r) => r.severity === filter.severity);
      }
      if (filter.source) {
        memoryErrors = memoryErrors.filter((r) => r.source === filter.source);
      }
      if (filter.resolved !== undefined) {
        memoryErrors = memoryErrors.filter((r) => r.resolved === filter.resolved);
      }
    }
    return [...(dbErrors || []), ...memoryErrors];
  }

  /**
   * Mark a system error as resolved by admin.
   */
  public async resolveError(errorId: string): Promise<boolean> {
    const record = this.errorRecords.find((r) => r.id === errorId);
    if (record) {
      record.resolved = true;
      record.resolvedAt = new Date().toISOString();
    }
    const dbResult = await systemErrorRepository.resolveError(errorId);
    return dbResult || Boolean(record);
  }

  /**
   * Clears registry records (for unit testing reset).
   */
  public clear(): void {
    this.errorRecords = [];
    this.idCounter = 1;
  }
}

export const systemErrorRegistry = SystemErrorRegistry.getInstance();
